"""sync-users: what makes a cluster's users match humans:/apps: in the db file
- the values.yaml (CNPG roles: list) change in its GitHub repo, and
- ALTER ROLE statements for humans whose password differs from SSM.
With --apply, after every db was read: one PR per repo with all its
values.yaml changes, wait for the roles to appear/go once merged and synced,
then set the passwords."""

from __future__ import annotations

import io
import sys
import time
from dataclasses import dataclass
from typing import Callable, TextIO

from .cluster import Cluster
from .config import DbConfig, SsmSettings
from .diff import print_diff
from .github import FileChange, GitHubError, RepoFile, get_file, open_pr
from .passwords import generate_password, password_matches, scram_verifier
from .ssm import ssm_create_password, ssm_passwords
from .values import RolesChange, sync_roles

POLL_SECONDS = 10


def password_plan(
    humans: list[str], passwords: dict[str, str], verifiers: dict[str, str]
) -> tuple[list[str], list[str]]:
    """(ALTER ROLE statements, one status line per human). Statements carry
    a SCRAM verifier, never the plaintext password."""
    statements, status = [], []
    for name in humans:
        if name not in verifiers:
            status.append(f"{name}: role not created yet — deploy values.yaml, then re-run")
        elif name not in passwords:
            status.append(f"{name}: no password in SSM (--apply generates one)")
        else:
            matches = password_matches(passwords[name], name, verifiers[name])
            if matches:
                status.append(f"{name}: in sync")
                continue
            status.append(f"{name}: {'no password set' if not verifiers[name] else 'differs' if matches is False else 'unknown hash format'}")
            quoted = '"' + name.replace('"', '""') + '"'
            statements.append(f"ALTER ROLE {quoted} PASSWORD '{scram_verifier(passwords[name])}';")
    return statements, status


def wait_for_roles(
    existing: Callable[[list[str]], set[str]],
    present: list[str],
    absent: list[str],
    timeout: float,
    sleep: Callable[[float], None] = time.sleep,
    clock: Callable[[], float] = time.monotonic,
    report: Callable[[float, set[str], set[str]], None] = lambda elapsed, missing, lingering: None,
) -> tuple[set[str], set[str]]:
    """Poll every POLL_SECONDS until every `present` role exists and no
    `absent` role does, or `timeout` seconds pass; returns (still missing,
    still there). `report` gets (elapsed, missing, lingering) after each
    poll that isn't done yet."""
    start = clock()
    deadline = start + timeout
    while True:
        roles = existing(present + absent)
        missing, lingering = set(present) - roles, set(absent) & roles
        if not (missing or lingering) or clock() >= deadline:
            return missing, lingering
        report(clock() - start, missing, lingering)
        sleep(min(POLL_SECONDS, max(deadline - clock(), 0)))


def waiting_line(elapsed: float, missing: set[str], lingering: set[str], initial: tuple[set[str], set[str]]) -> str:
    pending = [f"create {', '.join(sorted(missing))}"] if missing else []
    pending += [f"drop {', '.join(sorted(lingering))}"] if lingering else []
    state = "no changes detected yet" if (missing, lingering) == initial else "partly applied"
    return f"    {elapsed:.0f}s: {state} — waiting to {'; '.join(pending)}"


PR_BRANCH = "cnpg-users/sync"


def pr_body(plans: list[UsersPlan]) -> str:
    lines = ["Sync CNPG roles with the db files in cnpg-users-grants (`dbs/`):", ""]
    for p in plans:
        lines.append(f"**{p.db.name}** (`{p.db.values_file}`)")
        lines += [f"- {s}" for s in p.change.summary]
        lines.append("")
    lines.append("Generated by `cnpg-users.py sync-users --apply`; passwords are set after this is deployed.")
    return "\n".join(lines)


def drop_blocker_lines(rows: list[dict]) -> list[str]:
    """Report + SQL to clear what blocks DROP ROLE (CNPG can't drop a role that
    still owns objects or holds privileges)."""
    if not rows:
        return []
    lines = ["  before these roles can be dropped, run (as postgres, in each database):"]
    for r in rows:
        role = '"' + r["role"].replace('"', '""') + '"'
        owner = '"' + r["db_owner"].replace('"', '""') + '"'
        where = r["database"] or "(shared objects, any database)"
        lines.append(f"    {where}: {r['role']} owns {r['owned']}, holds {r['privileges']} privilege(s)")
        lines.append(f"      REASSIGN OWNED BY {role} TO {owner}; DROP OWNED BY {role};")
    return lines


@dataclass
class UsersPlan:
    db: DbConfig
    cluster: Cluster
    current: RepoFile     # values.yaml as read
    change: RolesChange   # values.yaml as it should be
    names: list[str]      # humans

    @property
    def values_pending(self) -> bool:
        return self.change.text != self.current.text


def plan_users(db: DbConfig, ssm: SsmSettings, apply: bool = False,
               out: TextIO = sys.stdout) -> tuple[bool, UsersPlan | None]:
    """Read phase (safe to run in parallel): write what isn't in sync to out
    (the values.yaml diff and, without apply, passwords that differ and
    their statements), or one line if everything is. Returns (anything
    differs, plan for apply_all)."""
    if not db.online:
        print(f"{db.header}: offline — skipped", file=out)
        return False, None
    if not (db.repo and db.values_file):
        sys.exit(f"{db.path}: repo and values_file are required for sync-users")

    try:
        current = get_file(db.repo, db.values_file)
    except GitHubError as exc:
        sys.exit(f"error fetching {db.repo}:{db.values_file}: {exc}")
    try:
        change = sync_roles(current.text, db.humans, db.apps, db.values_roles_path)
    except ValueError as exc:
        sys.exit(f"{db.repo}:{db.values_file}: {exc}")
    p = UsersPlan(db, Cluster(db), current, change, [h["name"] for h in db.present_humans])
    body = io.StringIO()
    if p.values_pending:
        print(f"  values.yaml ({db.repo}):", file=body)
        print_diff(current.text, change.text, db.values_file, indent="    ", out=body)
    if change.unlisted:
        print(f"  warning: in values.yaml but not in humans:/apps: {', '.join(change.unlisted)} (left as is)", file=body)
    blocked = drop_blocker_lines(p.cluster.drop_blockers(sorted(set(change.absent) | set(db.absent_humans))))
    for line in blocked:
        print(line, file=body)
    statements: list[str] = []
    if not apply:  # with apply, passwords are checked after the roles are in place
        statements, status = password_plan(p.names, ssm_passwords(ssm, p.names), p.cluster.password_verifiers(p.names))
        pending = [line for line in status if not line.endswith(": in sync")]
        if pending:
            print("  passwords:", file=body)
            for line in pending:
                print(f"    {line}", file=body)
        if statements:
            print("  statements:", file=body)
            for st in statements:
                print(f"    {st}", file=body)
    if not body.getvalue():
        print(f"{db.header}: {'values.yaml in sync' if apply else 'in sync'}", file=out)
    else:
        print(db.header, file=out)
        print(body.getvalue(), end="", file=out)
    return p.values_pending or bool(statements) or bool(blocked), p


def apply_all(plans: list[UsersPlan], ssm: SsmSettings, timeout: float = 180) -> bool:
    """Apply phase, after every db was read: one PR per repo with all its
    values.yaml changes, one wait for every affected cluster, then passwords
    db by db. True if anything still differs."""
    pending = [p for p in plans if p.values_pending]
    by_repo: dict[str, list[UsersPlan]] = {}
    for p in pending:
        by_repo.setdefault(p.db.repo, []).append(p)

    for repo, repo_plans in by_repo.items():
        files = ", ".join(p.db.values_file for p in repo_plans)
        print(f"\nCreating PR in {repo} ({len(repo_plans)} values file(s): {files})...", flush=True)
        changes = [FileChange(p.db.values_file, p.current.sha, p.change.text) for p in repo_plans]
        title = "cnpg users: sync " + ", ".join(p.db.name for p in repo_plans)
        try:
            pr = open_pr(repo, changes, PR_BRANCH, title, pr_body(repo_plans))
        except GitHubError as exc:
            sys.exit(f"error opening PR in {repo}: {exc}")
        note = {"opened": " (opened)", "updated": " (existing, rewritten)"}[pr.action]
        print(f"  PR{note}: {pr.url}", flush=True)

    still_pending: set[str] = set()
    if pending:
        # one wait for all clusters; keys are "<db>/<role>"
        by_name = {p.db.name: p for p in pending}
        present = [f"{p.db.name}/{n}" for p in pending for n in p.names]
        absent = [f"{p.db.name}/{n}" for p in pending for n in p.change.absent]

        def existing(keys: list[str]) -> set[str]:
            found = set()
            for db_name in sorted({k.split("/", 1)[0] for k in keys}):
                roles = [k.split("/", 1)[1] for k in keys if k.startswith(db_name + "/")]
                found |= {f"{db_name}/{r}" for r in by_name[db_name].cluster.existing_roles(roles)}
            return found

        summary = "; ".join(f"{p.db.name}: {', '.join(p.change.summary)}" for p in pending)
        print(f"\nwaiting up to {timeout:.0f}s for the PR(s) to be merged and synced ({summary}) ...", flush=True)
        initial: list[tuple[set[str], set[str]]] = []

        def report(elapsed: float, missing: set[str], lingering: set[str]) -> None:
            if not initial:
                initial.append((missing, lingering))
            print(waiting_line(elapsed, missing, lingering, initial[0]), flush=True)

        missing, lingering = wait_for_roles(existing, present, absent, timeout, report=report)
        if missing or lingering:
            print(f"  timed out — not created yet: {', '.join(sorted(missing)) or '-'};"
                  f" not dropped yet: {', '.join(sorted(lingering)) or '-'}")
            still_pending = {k.split("/", 1)[0] for k in missing | lingering}
        else:
            print("  roles confirmed on every cluster")

    drift = bool(still_pending)
    for p in plans:
        print(f"\n{p.db.name}: passwords", flush=True)
        drift |= set_passwords(p, ssm)
    sys.stdout.flush()
    return drift


def set_passwords(p: UsersPlan, ssm: SsmSettings) -> bool:
    """Generate missing SSM passwords, set the ones that differ; True if any still differ."""
    names, cluster = p.names, p.cluster
    passwords = ssm_passwords(ssm, names)
    for name in names:
        if name not in passwords:
            passwords[name] = generate_password()
            param = ssm_create_password(ssm, name, passwords[name])
            print(f"  generated a password for {name}: stored in SSM as {param}")
    statements, status = password_plan(names, passwords, cluster.password_verifiers(names))
    pending = [line for line in status if not line.endswith(": in sync")]
    if not pending:
        print("  in sync")
    for line in pending:
        print(f"  {line}")
    if not statements:
        return False
    cluster.set_passwords(statements)
    print(f"  set {len(statements)} password(s)")
    statements, status = password_plan(names, ssm_passwords(ssm, names), cluster.password_verifiers(names))
    for line in status:
        if not line.endswith(": in sync"):
            print(f"  still {line}")
    return bool(statements)
