"""sync-users: what makes a cluster's users match humans:/apps: in the db file
- the values.yaml (CNPG roles: list) change in its GitHub repo, and
- ALTER ROLE statements for humans whose password differs from SSM.
With --apply: open a PR per values.yaml, wait for the roles to appear/go
once it's merged and synced, then set the passwords."""

from __future__ import annotations

import sys
import time
from typing import Callable

from .cluster import Cluster
from .config import DbConfig, SsmSettings
from .diff import print_diff
from .github import GitHubError, get_file, open_pr
from .passwords import generate_password, password_matches, scram_verifier
from .ssm import ssm_create_password, ssm_passwords
from .values import RolesChange, sync_roles

POLL_SECONDS = 10


def password_plan(
    humans: list[str], passwords: dict[str, str], verifiers: dict[str, str]
) -> tuple[list[str], list[str]]:
    """(ALTER ROLE statements, one status line per human). Statements carry
    a SCRAM verifier, never the plaintext password."""
    statements, status = [], []
    for name in humans:
        if name not in verifiers:
            status.append(f"{name}: role not created yet — deploy values.yaml, then re-run")
        elif name not in passwords:
            status.append(f"{name}: no password in SSM (--apply generates one)")
        else:
            matches = password_matches(passwords[name], name, verifiers[name])
            if matches:
                status.append(f"{name}: in sync")
                continue
            status.append(f"{name}: {'no password set' if not verifiers[name] else 'differs' if matches is False else 'unknown hash format'}")
            quoted = '"' + name.replace('"', '""') + '"'
            statements.append(f"ALTER ROLE {quoted} PASSWORD '{scram_verifier(passwords[name])}';")
    return statements, status


def wait_for_roles(
    existing: Callable[[list[str]], set[str]],
    present: list[str],
    absent: list[str],
    timeout: float,
    sleep: Callable[[float], None] = time.sleep,
    clock: Callable[[], float] = time.monotonic,
    report: Callable[[float, set[str], set[str]], None] = lambda elapsed, missing, lingering: None,
) -> tuple[set[str], set[str]]:
    """Poll every POLL_SECONDS until every `present` role exists and no
    `absent` role does, or `timeout` seconds pass; returns (still missing,
    still there). `report` gets (elapsed, missing, lingering) after each
    poll that isn't done yet."""
    start = clock()
    deadline = start + timeout
    while True:
        roles = existing(present + absent)
        missing, lingering = set(present) - roles, set(absent) & roles
        if not (missing or lingering) or clock() >= deadline:
            return missing, lingering
        report(clock() - start, missing, lingering)
        sleep(min(POLL_SECONDS, max(deadline - clock(), 0)))


def waiting_line(elapsed: float, missing: set[str], lingering: set[str], initial: tuple[set[str], set[str]]) -> str:
    pending = [f"create {', '.join(sorted(missing))}"] if missing else []
    pending += [f"drop {', '.join(sorted(lingering))}"] if lingering else []
    state = "no changes detected yet" if (missing, lingering) == initial else "partly applied"
    return f"    {elapsed:.0f}s: {state} — waiting to {'; '.join(pending)}"


def pr_body(db: DbConfig, change: RolesChange) -> str:
    lines = [f"Sync CNPG roles of `{db.cluster}` in `{db.namespace}` with `dbs/{db.path.name}` (cnpg-users-grants-cli):", ""]
    lines += [f"- {s}" for s in change.summary]
    lines += ["", "Generated by `cnpg-users.py sync-users --apply`; passwords are set after this is deployed."]
    return "\n".join(lines)


def cmd_sync_users(db: DbConfig, ssm: SsmSettings, apply: bool = False, timeout: float = 180) -> bool:
    """Print (and with apply, carry out) the values.yaml change and password
    statements; True if anything still differs."""
    print(f"== {db.name} ==")
    print(f"cluster {db.cluster} in ns {db.namespace}")
    if not db.online:
        print("(offline — skipped)")
        return False
    if not (db.repo and db.values_file):
        sys.exit(f"{db.path}: repo and values_file are required for sync-users")

    try:
        current = get_file(db.repo, db.values_file)
    except GitHubError as exc:
        sys.exit(f"error fetching {db.repo}:{db.values_file}: {exc}")
    try:
        change = sync_roles(current.text, db.humans, db.apps)
    except ValueError as exc:
        sys.exit(f"{db.repo}:{db.values_file}: {exc}")
    print(f"\n  values.yaml ({db.repo}):")
    print_diff(current.text, change.text, db.values_file, indent="    ")

    cluster = Cluster(db)
    names = [h["name"] for h in db.humans]
    values_pending = change.text != current.text
    if values_pending and apply:
        title = f"cnpg users: sync {db.name}"
        print(f"\n  Creating PR in {db.repo}...", flush=True)
        try:
            url = open_pr(db.repo, db.values_file, current.sha, change.text,
                          f"cnpg-users/{db.name}", title, pr_body(db, change))
        except GitHubError as exc:
            sys.exit(f"error opening PR in {db.repo}: {exc}")
        print(f"  PR: {url}")
        print(f"  waiting up to {timeout:.0f}s for it to be merged and synced"
              f" ({', '.join(change.summary)}) ...", flush=True)
        initial: list[tuple[set[str], set[str]]] = []

        def report(elapsed: float, missing: set[str], lingering: set[str]) -> None:
            if not initial:
                initial.append((missing, lingering))
            print(waiting_line(elapsed, missing, lingering, initial[0]), flush=True)

        missing, lingering = wait_for_roles(cluster.existing_roles, names, change.absent, timeout, report=report)
        if missing or lingering:
            print(f"  timed out — not created yet: {', '.join(sorted(missing)) or '-'};"
                  f" not dropped yet: {', '.join(sorted(lingering)) or '-'}")
        else:
            print("  roles confirmed: all humans exist" + (f", dropped {', '.join(change.absent)}" if change.absent else ""))
            values_pending = False

    passwords = ssm_passwords(ssm, names)
    if apply:
        for name in names:
            if name not in passwords:
                passwords[name] = generate_password()
                param = ssm_create_password(ssm, name, passwords[name])
                print(f"\n  generated a password for {name}: stored in SSM as {param}")
    statements, status = password_plan(names, passwords, cluster.password_verifiers(names))
    print("\n  passwords:")
    for line in status:
        print(f"    {line}")
    if statements:
        if apply:
            cluster.set_passwords(statements)
            print(f"\n  set {len(statements)} password(s)")
            statements, status = password_plan(names, ssm_passwords(ssm, names), cluster.password_verifiers(names))
            for line in status:
                if not line.endswith(": in sync"):
                    print(f"    still {line}")
        else:
            print("\n  statements:")
            for s in statements:
                print(f"    {s}")
    return values_pending or bool(statements)
